services:
  postgres:
    container_name: postgres
    image: bitnami/postgresql
    environment: 
      POSTGRES_USER: kaio_dias
      POSTGRES_PASSWORD: kaio_dias
      PGDATA: /data/postgres
    ports: 
      - "5432:5432"
    networks: 
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container     
    image: bitnami/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: kaio.dias@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin@
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"  
    networks:
      - postgres_network 
    restart: unless-stopped

  networks:
    postgres:
      driver: bridge
  
  volumes:
    postgres:
    pgadmin:          

